# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4224ecb289a0417500947d0a4b121ddd"
application_url = "https://uganda-experience-nutrition-mention.trycloudflare.com"
embedded = true
name = "learning-test"
handle = "learning-test-3"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://uganda-experience-nutrition-mention.trycloudflare.com/auth/callback",
  "https://uganda-experience-nutrition-mention.trycloudflare.com/auth/shopify/callback",
  "https://uganda-experience-nutrition-mention.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
